### ISSUE TITLE
When changing language, the diff shown is still from the previously-selected wiki

### ISSUE THREAD

**Issue by hrasyid** [google/wikiloop-battlefield#134] opened 2019-12-26 22:00 UTC
To repro:
1) Open the [main URL](http://battlefield.wikiloop.org/), which default to English
2) change Wiki using the selector, let's say to French (fr)
3) The UI language changes to French but the diff shown is still from the English Wikipedia. Only if you evaluate the current diff (e.g. by choosing "not sure") and then wait for the "next" button to appear will you get a diff from the French Wikipedia.

This might confuse the user into thinking that the selector doesn't work, and the workaround (evaluate the current diff so that the next button shows up) isn't obvious so they may be stuck without realizing how to proceed.

I suggest when the user changes the wiki/language from the selector, the page refresh so that a diff from the newly selected language shows up.

Example screenshot:
![CKD44OYW9n2](https://user-images.githubusercontent.com/4159519/71491817-e0c29a80-27e7-11ea-8331-3c7ef18f7bb5.png)

**Comment by xinbenlv** [comment] 2019-12-26 22:15
Duplicate of #122

**Comment by xinbenlv** [comment] 2019-12-26 22:48
Thank you @hrasyid 
If you like to help fix it, here are two code points:

1. Load the next revison to show (https://github.com/google/wikiloop-battlefield/blob/b984f098dc703e9a02f907187ffabf748e07bcbb/pages/index.vue#L58)
2. Switching the language https://github.com/google/wikiloop-battlefield/blob/b984f098dc703e9a02f907187ffabf748e07bcbb/layouts/default.vue#L47

So one of the implementation option is when the language is being switched out, we can generate an event from `default.vue`,  and page `index.vue` subscribe to such event and load next.

Here is an example of emitting a custom event from vue component 
https://github.com/google/wikiloop-battlefield/blob/3e820ae859065d6c497807b8a307d5f202da472a/components/RevisionCard.vue#L431

Give it a try and let me know if you have any questions.

**Closed** 2019-12-27 22:16 UTC
Labels: bug
